### ISSUE TITLE
Simplify build step

### ISSUE THREAD

**Issue by onbjerg** [AlexanderLindsay/dailybudgeteer#2]
It takes a really long time. Also maybe we could have a build step with no interaction?

**Comment by AlexanderLindsay** [comment]
I will take a look at this.

Do you mean the initial npm install or the npm run build? If you mean npm run build, what timings does gulp show for you?

**Comment by onbjerg** [comment]
Both were pretty slow. I'll reinstall again tomorrow and send you some timings.

**Comment by AlexanderLindsay** [comment]
That would be cool, but don't worry about it if it is too much trouble. I just wanted to get a rough sense of how long it was taking you so I could see if it is in the same ballpark as mine. I did a rough estimate of the build time I am seeing and it was about 8 seconds all told. Are getting something astronomically more than that?

I am pretty sure there are a lot of things I can improve about the whole build process. I am new to the whole workflow I am using in this project (gulp, npm) and things like electron and semantic-ui and typescript added further complications. I need to go back over it and figure out what part is magic and what part is real.

**Comment by onbjerg** [comment]
I am getting something way above 8 seconds. It took me several minutes.

**Comment by AlexanderLindsay** [comment]
I am sort of at a loss. How much are you willing to look into this?

I know the `npm install` takes a couple minutes, but that should be a one time thing.
